name: Plugin1
version: '${project.version}'
main: dizzillian.xyz.plugin1.Plugin1
api-version: 1.18
commands:
  sleep:
    description: Sleep by using this command.
    permission: op
  healme:
    description: Heal yourself.
    permission: op
  feedme:
    description: Feed yourself.
    permission: op
  smkick:
    description: Kick players out of your smp.
    permission: op
  smban:
    description: .
    permission: op
  freeze:
    description: Freeze a player.
    permission: op
  unfreeze:
    description: Unfreeze a player.
    permission: op
  test:
    description: Test from config.
  smreload:
    description: Relaods smp essentials.
    permission: op
  death:
    description: testing death from config.
    permission: op

